### ISSUE TITLE
Обработка ошибок пользовательского ввода

### ISSUE THREAD

**Issue by Const-Phi** [kekafon/DBMS#2]
# Проблемы взаимодействия с пользователем
Взаимодействие с пользователем, как правило, сопряжено с рядом проблем, относящихся как к удобству использования разрабатываемого ПО (_usability_), так и к обеспечению устойчивого функционирования разрабатываемого ПО, при эксплуатации реальными пользователями (_sustainability_).

## Удобство
Данный пункт носит скорее рекомендательный характер. Но пользователю крайне сложно понять, что же от него ожидает ПО, глядя на мигающий курсор без какой-либо предваряющей подсказки. Я бы добавил некоторое сообщение, позволяющее пользователю принять решение о вводе:
```python
size = int(input('Введите размер массива'))
```

## Ввод не числа
В приведённом коде есть место, в котором происходит преобразование типа
```python
size = int(input())
```

`input()` возвращает строку, которую функция `int` пытается сконвертировать к целому числу. Если это удаётся, то в переменную попадает это число, в противном случае получаем исключительную ситуацию, в частности [`ValueError`](https://docs.python.org/3/library/exceptions.html#ValueError).

## Ввод числа, лежащего вне допустимого диапазона

В коде функции поиска минимального элемента есть место получения нулевого (первого) элемента
```python
  min = values[0]
```
`range(size)` для неположительного значения `size` вернёт `[]`, а следовательно, данная часть кода приведёт к возникновению исключительной ситуации [`IndexError`](https://docs.python.org/3/library/exceptions.html#IndexError).

## Резюме
Можно рассмотреть несколько ситуаций

| Статус | Ситуация | Пример | Результат |
| :---: | --- | --- | --- |
| ❌  | Пользовательский ввод не число | `Hello` | `ValueError: invalid literal for int() with base 10: 'Hello'`
| ❌  | Пользовательский ввод число, вне допустимого диапазона | `-1` | `IndexError: list index out of range`
| ✔️  | Пользовательский ввод допустимое число | `25` | `4.691535677824055`

**Comment by D-mercool** [comment]
Починил.

**Comment by Const-Phi** [comment]
Принято, закрываю.
