### ISSUE TITLE
Рефакторинг и небольшие улучшения

### ISSUE THREAD

**Issue by Const-Phi** [kekafon/DBMS#3]
## Рефакторинг
Не вполне ясна тяга к числу `100`, хотя и в случае ограничения диапазона случайных значений она, быть может, оправдана. Но касательно размера последовательности остаётся загадочной, особенно в свете [изменений](https://docs.python.org/3.1/whatsnew/3.0.html#integers), произошедших в языке при переходе к версии 3.

### Функция получения размера последовательности
Функцию `enter_size()` стоит пересмотреть в части [использования _непоименованных_ констант в коде](https://ru.wikipedia.org/wiki/Магическое_число_(программирование)#Плохая_практика_программирования). Кажется, что число `100` (дважды указанное явно) стоит убрать в константу (тогда речь про _честный_ рефакторинг) или в параметр функции как значение по умолчанию (в этом случае рефакторинг будет не совсем честным, так как хоть и поведение не изменилось, но API был затронут, хоть и в сторону расширения &ndash; допустимо, если без фанатизма трактовать [терминологию](https://ru.wikipedia.org/wiki/Рефакторинг#Рефакторинг_кода)). Например, можно проделать что-то вроде
```python
def enter_size(maxSize = 100):
    while True:
        try:
            size = int(input(f'Введите размер массива (больше нуля и меньше {maxSize}): '))
            if 0 < size <= maxSize:
# ...
```
### Функция получения последовательности
Также кажется обоснованным вынесение способа получения последовательности (тестовых) данных в отдельную функцию &ndash; `get_random_values(size, min = 1, max = 100)`. Впрочем, небезосновательным было бы желание автора разделить и эту функцию на логически замкнутые блоки &ndash; получение последовательности псевдослучайных значений и получение одного псевдослучайного значения. 
```python
def get_random_value(min = 1, max = 100)
    return random.uniform(min, max)

def get_random_values(size, min = 1, max = 100)
    return [get_random_value(min, max) for _ in range(size)]
```
Хотя функция `get_random_value` может и оказаться избыточной; а её добавление остаётся на ~совести~ усмотрение автора.

## Улучшения
Все улучшения касаются в основном текстовых сообщений.
1. Кажется, что сообщение `'Введите размер массива (больше нуля и меньше 100): '` может ввести пользователя в заблуждение, так как буквально в следующей строке следует проверка `0 < size <= 100`, в которой верхняя граница очерчена [нестрогим неравенством](https://ru.wikipedia.org/wiki/Неравенство), в отличие от нижней. Таким образом, стоит внести изменения либо в текст сообщения, либо в условия проверки допустимости введённого пользователем значения.
1. В сообщении `'Введенной число не соответствует заданному диапазону. Попробуйте еще раз'` допущена досадная опечатка &ndash; очевидно, что автор имел ввиду `'Введенное число...'`, при этом использование (а равно и не использование) буквы ё остаётся на усмотрение автора.
1. Сообщение `'Вы ввели не число. Попробуйте еще раз'` не вполне корректно, так как такая же реакция воспоследует и на пользовательский ввод представленный числом с плавающей точкой (сиречь вещественного числа). Такое досадное недоразумение происходит в связи с тем, что формат числа с плавающей точкой не удовлетворяет требованиям, предъявляемым к числу целому. Иными словами пользовательский ввод `3.14` приведёт к `ValueError` и соответствующим заверениям, что вещественное число &ndash; вовсе и не число.
1. _And last but not least_, перед победной демонстрацией минимального элемента последовательности не дурно было бы и саму последовательность предъявить пользователю дабы он сам мог во всём удостовериться.

**Comment by D-mercool** [comment]
Исправил, спасибо за замечания )

**Comment by Const-Phi** [comment]
Молодец! Это уже начинает напоминать нормально поставленный процесс 👍
